depts/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from gus_depts.views import index as gus_depts_index

from rest_framework import routers
from gus_depts.views import DeptViewSet
import gus_depts.urls as gus_depts_urls


router = routers.DefaultRouter()
router.register(r'depts', DeptViewSet)

urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^$', gus_depts_index, name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^depts/', include(gus_depts_urls, namespace="gus_depts")),

]

gus_depts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # url(r'^$', views.index, name='index'),
    url(r'^(?P<dept_id>[0-9]+)/$', views.detail, name='detail'),
    # url(r'^$', views.IndexView.as_view(), name='index'),
    # url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

gus_depts/models.py
from django.db import models

class Department(models.Model):
    full_name = models.CharField(max_length=150)
    abbreviation = models.CharField(max_length=5)
    # TODO set this as null=true and do not let blanks in the database
    web_url = models.CharField(max_length=200, blank=True)
    server_uri = models.URLField(max_length=200)

    def __str__(self):
        return '%s (%s)' % (self.full_name, self.abbreviation)

gus_depts/views.py
from django.shortcuts import get_object_or_404, render

from .models import Department

from rest_framework import viewsets
from .serializers import DeptSerializer


def index(request):
    latest_depts_list = Department.objects.order_by('abbreviation')
    return render(request, 'gus_depts/index.html', {'latest_depts_list': latest_depts_list})

def detail(request, dept_id):
    dept = get_object_or_404(Department, pk=dept_id)
    return render(request, 'gus_depts/detail.html', {'dept': dept})

class DeptViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows departments to be viewed or edited.
    """
    queryset = Department.objects.all()
    serializer_class = DeptSerializer

gus_depts/templates/gus_depts/base.html
{% load staticfiles %}
<html>
  <head>
    <title>Departments</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static "base.css" %}" rel="stylesheet">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
  </head>
  <body>
    <div id="wrap">
    <!-- Begin page content -->
    <div class="container depts">
      <div class="page-header">
        <h1>Departments using gus</h1>
      </div>
      {% block content %}{% endblock %}
    </div> <!-- wrap -->
    </body>
</html>

gus_depts/templates/gus_depts/detail.html
{% extends "gus_depts/base.html" %}
{% block content %}
<p class="lead">{{ dept.full_name }} ({{dept.abbreviation}})</p>
<dl class="dl-vertical">
  {% if dept.server_uri %}
    <dt>Server uri: </dt>
    <dd><a href="{{dept.server_uri}}">{{dept.server_uri}}</a></dd>
  {% endif %}  
  {% if dept.web_url %}
    <dt>Web url: </dt>
    <dd><a href="{{dept.web_url}}">{{dept.web_url}}</a></dd>
  {% endif %}
</dl>
  <div style="text-align:right">
      <a href="/">back to listings</a>
  </div>
{% endblock %}

gus_depts/templates/gus_depts/index.html
{% extends "gus_depts/base.html" %}

{% block content %}
{% if latest_depts_list %}

    <table class="table table-striped table-hover">

    {% for dept in latest_depts_list %}
        <tr class="{% cycle 'active' 'success' %}">
          <td class="col-xs-5">
            <a href="{% url 'gus_depts:detail' dept.id %}">{{ dept.full_name }}</a>
          </td>
          <td class="col-xs-4">
            {{dept.server_uri}}
          </td>
          <td class="col-xs-3">
            <a href="{% url 'gus_depts:detail' dept.id %}">{{ dept.abbreviation }}</a>
          </td>
        </tr>
    {% endfor %}

  </table>

{% else %}

    <p>No dept are available.</p>

{% endif %}
{% endblock %}